language: python

sudo: false

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install rwlock
  - pip install pytest
  - pip install redis

install:
  - pip install coveralls

script:
  - python setup.py test
  - pytest tests/*

after_success:
  - coveralls
